SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

-- 1. Menyu qruplarının sorğusu
SELECT 
    [MenuGroupID],
    [MenuGroupKey],
    [MenuGroupText],
    [DisplayIndex],
    [MenuGroupActive],
    [SecLangMenuGroupText],
    [PictureName],
    [ShowCaption],
    [HideInDineIn],
    [HideInBar],
    [HideInTakeaway],
    [HideInCounter],
    [HideInDelivery],
    [ButtonColor],
    [RevenueCenterTypeID],
    [DeleteReason],
    [CustomField1],
    [CustomField2],
    [CustomField3],
    [CustomField4],
    [CustomField5],
    [EditKey],
    [SyncKey],
    [BranchID],
    [AddUserID],
    [AddDateTime],
    [EditUserID],
    [EditDateTime]
FROM [MenuGroups];

-- 2. Menyu məhsullarının sorğusu
SELECT 
    MenuItems.AutoID, 
    MenuItems.MenuItemID, 
    ISNULL(MenuItems.MainMenuItemID, 0) AS MainMenuItemID, 
    MenuItems.RevenueCenterTypeID, 
    MenuItems.MenuItemText, 
    MenuItems.MenuCategoryID, 
    MenuItems.MenuGroupID, 
    MenuItems.DisplayIndex AS DisplayIndex2, 
    MenuItems.DefaultUnitPrice, 
    MenuItems.MenuItemCost, 
    MenuItems.MenuItemDescription, 
    MenuItems.MenuItemNotification, 
    MenuItems.MenuItemActive, 
    MenuItems.MenuItemInStock, 
    MenuItems.MenuItemTaxable, 
    ISNULL(TaxGroups.TaxRate, 8) AS TaxPercent, 
    MenuItems.MenuModifierID, 
    MenuItems.MenuItemDiscountable, 
    MenuItems.MenuItemPopUpHeaderID, 
    MenuItems.MenuItemPopUpChoiceText, 
    MenuItems.HasModifierPopUps, 
    ISNULL(MenuItems.SecLangMenuItemText, '') AS SecLangMenuItemText, 
    MenuItems.SecLangPopUpChoiceText, 
    MenuItems.PictureName, 
    MenuItems.ShowCaption, 
    ISNULL(MenuItems.IsComboMenu, 0) AS IsComboMenu,
    ISNULL(MenuItems.IsTopMenu, 0) AS IsTopMenu, 
    MenuItems.ButtonColor, 
    ISNULL(MenuItems.Barcode, '') AS Barcode,
    ISNULL(MenuItems.Barcode2, '') AS Barcode2, 
    MenuItems.ItemDelCharge, 
    MenuItems.ItemDelComp, 
    MenuItems.DineInPrice, 
    MenuItems.BarTabPrice, 
    MenuItems.TakeOutPrice, 
    MenuItems.DriveThruPrice, 
    MenuItems.DeliveryPrice, 
    MenuItems.OrderByWeight, 
    MenuItems.PrintPizzaLabel, 
    MenuItems.KitchenSortNumber, 
    MenuItems.ModBuilderTemplateID, 
    MenuItems.MenuItemTypeID, 
    ISNULL(MenuItems.AccountingCode, '') AS AccountingCode, 
    ISNULL(MenuItems.PrintOnLabel, 0) AS PrintOnLabel, 
    MenuItems.UsedPrinterID1, 
    MenuItems.UsedPrinterID2, 
    MenuItems.UsedPrinterID3, 
    MenuItems.UsedPrinterID4, 
    MenuItems.UsedPrinterID5, 
    MenuItems.SecurityLevel, 
    MenuItems.DeleteReason, 
    MenuItems.CustomField1, 
    MenuItems.CustomField2, 
    MenuItems.CustomField3, 
    MenuItems.CustomField4, 
    MenuItems.CustomField5, 
    MenuItems.EditKey, 
    MenuItems.SyncKey, 
    MenuItems.BranchID, 
    MenuItems.AddUserID, 
    MenuItems.AddDateTime, 
    MenuItems.EditUserID, 
    ISNULL(MenuItems.UseKds1, 0) AS UseKds1, 
    ISNULL(MenuItems.UseKds2, 0) AS UseKds2, 
    ISNULL(MenuItems.UseKds3, 0) AS UseKds3,
    ISNULL(MenuItems.UseKds4, 0) AS UseKds4, 
    ISNULL(MenuItems.UseKds5, 0) AS UseKds5,
    ISNULL(MenuItems.UseKds6, 0) AS UseKds6,
    ISNULL(MenuItems.UseKds7, 0) AS UseKds7,
    ISNULL(MenuItems.UseKds8, 0) AS UseKds8, 
    ISNULL(MenuItems.UseKds9, 0) AS UseKds9,
    ISNULL(MenuItems.UseKds10, 0) AS UseKds10, 
    MenuItems.CountDownDate, 
    ISNULL(MenuItems.CountDownValue, 0.0) AS CountDownValue,
    ISNULL(MenuItems.CountDownActualResult, 0.0) AS CountDownActualResult,  
    MenuItems.EditDateTime, 
    MenuCategories.MenuCategoryText, 
    MenuSubCategories.MenuSubCategoryText, 
    TaxGroups.GroupName AS TaxGroupText, 
    MenuModifierGroups.MenuModifierGroupText AS MenuModifierText, 
    MenuItems.DisplayIndex AS MenuDisplayIndex, 
    MenuItems.MenuItemKey, 
    MenuItems.MainMenuItemKey, 
    MenuItems.MenuItemGlobalKey, 
    MenuItems.MenuCategoryKey, 
    MenuItems.MenuGroupKey, 
    MenuItems.TaxGroupID, 
    MenuItems.TaxGroupKey, 
    MenuItems.MenuModifierKey, 
    MenuItems.MenuModifierForcedID, 
    MenuItems.MenuModifierForcedKey, 
    MenuForcedModifierGroups.MenuModifierGroupText AS MenuForcedModifierText,
    efr_Branchs.BranchName,
    MenuItemLayout.DisplayIndex AS DisplayIndex,
    MenuItemLayout.MenuGroupID AS MenuScreenGroupID,
    MenuItemLayout.MenuGroupKey AS MenuScreenGroupKey 
FROM MenuItems  
LEFT OUTER JOIN MenuModifierGroups AS MenuForcedModifierGroups 
    ON MenuItems.MenuModifierForcedKey = MenuForcedModifierGroups.MenuModifierGroupKey 
LEFT OUTER JOIN MenuModifierGroups 
    ON MenuItems.MenuModifierKey = MenuModifierGroups.MenuModifierGroupKey 
LEFT OUTER JOIN MenuSubCategories 
    ON MenuItems.MenuGroupKey = MenuSubCategories.MenuSubCategoryKey 
LEFT OUTER JOIN MenuCategories 
    ON MenuItems.MenuCategoryKey = MenuCategories.MenuCategoryKey 
LEFT OUTER JOIN TaxGroups 
    ON MenuItems.TaxGroupID = TaxGroups.TaxGroupID  
LEFT OUTER JOIN efr_Branchs 
    ON MenuItems.BranchID = efr_Branchs.BranchID 
INNER JOIN MenuItemLayout 
    ON MenuItemLayout.MenuItemID = MenuItems.AutoID 
WHERE MenuItemLayout.MenuGroupID = 7;