SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

-- 1. Dil Parametrlərinin Sorğusu
SELECT 
    [ParamName], 
    [ParamValue],
    [EditKey],
    [SyncKey] 
FROM [Params] 
WHERE ParamName LIKE 'lang%';

-- 2. Masa Qruplarının Sorğusu
SELECT 
    [AutoID], 
    [TableGroupID], 
    [TableGroupKey], 
    [TableGroupText], 
    [RevenueCenterTypeID], 
    [DeleteReason], 
    [CustomField1], 
    [CustomField2], 
    [CustomField3], 
    [CustomField4], 
    [CustomField5], 
    [EditKey], 
    [SyncKey], 
    [BranchID], 
    [AddUserID], 
    [AddDateTime], 
    [EditUserID], 
    [EditDateTime], 
    ISNULL(TableRowCount, 8) AS TableRowCount, 
    ISNULL(TableColumnCount, 9) AS TableColumnCount  
FROM [DineInTableGroups];

-- 3. Stansiya Parametrlərinin Sorğusu (StationID = 1)
SELECT 
    [AutoID], 
    [StationID], 
    [StationName], 
    [AllowRegister], 
    [DefineValue], 
    [ActivateCashier], 
    [RememberCashier], 
    [BackgroundPicture], 
    [SideBarPicture], 
    [DefaultLoginEntrance], 
    [DefultTablePlan], 
    [SkinName], 
    [ShowDineInButton], 
    [ShowTakeOutButton], 
    [ShowDriveThruButton], 
    [ShowDeliveryButton], 
    [ShowRecallButton], 
    [ShowDriverStatusButton], 
    [ShowTimeCardButton], 
    [ShowOperationsButton], 
    [ShowBackOfficeButton], 
    [ShowQuickServiceDineIn], 
    [ShowQuickServiceTakeOut], 
    [ShowQuickServiceDriveThru], 
    [ShowQuickServiceDelivery], 
    [StayInOrderScreenTakeOut], 
    [StayInOrderScreenDriveThru], 
    [StayTablePlanInDineIn], 
    [TimeOutScreenLock], 
    [IsMobile], 
    [CustomerDisplayPortNo], 
    [CustomerDisplayLine1], 
    [CustomerDisplayLine2], 
    [WeightScale1PortNo], 
    [WeightScale1BaudRate], 
    [WeightScale2PortNo], 
    [WeightScale2BaudRate], 
    [CashRegisterModel], 
    [CashRegisterBaudRate], 
    [CashRegisterDataDelay], 
    [CashRegisterLineDelay], 
    [CashRegisterStations], 
    [CashRegisterPortNo], 
    [PaymentOverTime], 
    [DirectOpenOrderInEditMode], 
    [PrintVoidedLinesOnGuestCheck], 
    [StationKey], 
    ISNULL([AskPasswordForReduce], 0) AS [AskPasswordForReduce], 
    ISNULL([MediaDisplayIsActive], 0) AS [MediaDisplayIsActive], 
    [MediaDisplayOnWaiting], 
    [MediaDisplayOnSale], 
    ISNULL([MediaDisplayClosedMessage], 'KASA KAPALIDIR') AS [MediaDisplayClosedMessage], 
    ISNULL([MediaDisplayMoneyOver], 'TEŞEKKÜR EDERİZ') AS [MediaDisplayMoneyOver], 
    [EditKey], 
    [SyncKey],
    ISNULL(ShowCashTrayButton, '') AS ShowCashTrayButton,
    ISNULL(DisableSaleOnOpenCashTray, '') AS DisableSaleOnOpenCashTray,
    BekoPosDesign,
    BekoPosOutput,
    BekoPosDatabase,
    ISNULL(EnableCallCenterClient, 0) AS EnableCallCenterClient, 
    [CallCenterClientAddress],
    ISNULL(ShowScaleOrderDineIn, 0) AS ShowScaleOrderDineIn,
    ISNULL(ShowScaleOrderTakeOut, 0) AS ShowScaleOrderTakeOut,
    ISNULL(ShowScaleOrderDriveThru, 0) AS ShowScaleOrderDriveThru,
    ISNULL(ShowScaleOrderDelivery, 0) AS ShowScaleOrderDelivery,
    ISNULL(UseRetailMode, 0) AS UseRetailMode,
    ISNULL(StaticPluNumber, 0) AS StaticPluNumber,
    ISNULL(UseStaticPlu, 0) AS UseStaticPlu,
    ISNULL(EnableCentralCallCenterClient, 0) AS EnableCentralCallCenterClient,
    ISNULL(CentralCallCenterClientAddress, '') AS CentralCallCenterClientAddress,
    ISNULL(UseSecondLangOnKitchenPrint, 0) AS UseSecondLangOnKitchenPrint,
    ISNULL(CallerIDPort, '') AS CallerIDPort,
    ISNULL(MediaDisplayFontSize, 40) AS MediaDisplayFontSize,
    ISNULL(SendTareOnWeightMinus, 0) AS SendTareOnWeightMinus,
    ISNULL(SendTareOnAfterAddButton, 0) AS SendTareOnAfterAddButton,
    ISNULL(ShowScaleOrderRetail, 0) AS ShowScaleOrderRetail,
    ISNULL(ShowComboOnMediaDisplay, 0) AS ShowComboOnMediaDisplay,
    ISNULL(ShowMenuModifierOnMediaDisplay, 0) AS ShowMenuModifierOnMediaDisplay,
    ISNULL(ShowPicturedModifierOnMediaDisplay, 0) AS ShowPicturedModifierOnMediaDisplay,
    ISNULL(ShowSidePictureOnMediaDisplay, 0) AS ShowSidePictureOnMediaDisplay,
    ISNULL(ScaleMode, '0') AS ScaleMode,
    ISNULL(ShowCashDiscountButtonOnMainScreen, '0') AS ShowCashDiscountButtonOnMainScreen, 
    ISNULL(HideOkButtonOnDineIn, 0) AS [HideOkButtonOnDineIn], 
    ISNULL(HideOkButtonOnDelivery, 0) AS [HideOkButtonOnDelivery], 
    ISNULL(HideOkButtonOnDriveThru, 0) AS [HideOkButtonOnDriveThru], 
    ISNULL(HideOkButtonOnTakeOut, 0) AS [HideOkButtonOnTakeOut] 
FROM [StationSettings]  
WHERE StationID = 1;

-- 4. Printerlərin Sorğusu
SELECT 
    [AutoID], 
    [PrinterID], 
    [PrinterName],
    [EditKey],
    [SyncKey]  
FROM [Printers];

-- 5. Çap Dizaynlarının Sorğusu
SELECT 
    [AutoID], 
    [DesignKey], 
    [DocumentTypeID], 
    [DesignName], 
    [DesignData], 
    [IsDefault],
    [EditKey],
    [SyncKey]  
FROM [PrinterDesigns];

-- 6. Stansiya Çap Parametrlərinin Sorğusu (StationID = 1)
SELECT 
    AutoID, 
    StationID, 
    CheckPrinterName, 
    CheckAltPrinterName, 
    CheckPrinterID, 
    CheckDesignPath, 
    DeliveryPrinterName, 
    DeliveryAltPrinterName, 
    DeliveryPrinterID,  
    DeliveryDesignPath, 
    InvoicePrinterName, 
    InvoiceAltPrinterName, 
    InvoicePrinterID, 
    InvoiceDesignPath, 
    InvoiceRowCount, 
    ReportPrinterName, 
    ReportAltPrinterName,  
    ReportPrinterID, 
    ReportDesignPath, 
    AdditionPrinterName, 
    AdditionPrinterID, 
    AdditionDesignPath, 
    AdditionRowCount, 
    ReportA4PrinterName, 
    ReportA4AltPrinterName,  
    ReportA4PrinterID, 
    ReportA4DesignPath, 
    Kitchen1PrinterName, 
    Kitchen1AltPrinterName, 
    Kitchen1PrinterID, 
    Kitchen1DesignPath, 
    Kitchen2PrinterName,  
    Kitchen2AltPrinterName, 
    Kitchen2PrinterID, 
    Kitchen2DesignPath, 
    Kitchen3PrinterName, 
    Kitchen3AltPrinterName, 
    Kitchen3PrinterID, 
    Kitchen3DesignPath,  
    Kitchen4PrinterName, 
    Kitchen4AltPrinterName, 
    Kitchen4PrinterID, 
    Kitchen4DesignPath, 
    Kitchen5PrinterName, 
    Kitchen5AltPrinterName, 
    Kitchen5PrinterID,  
    Kitchen5DesignPath, 
    Kitchen6PrinterName, 
    Kitchen6AltPrinterName, 
    Kitchen6PrinterID, 
    Kitchen6DesignPath, 
    Kitchen7PrinterName, 
    Kitchen7AltPrinterName,  
    Kitchen7PrinterID, 
    Kitchen7DesignPath, 
    Kitchen8PrinterName, 
    Kitchen8AltPrinterName, 
    Kitchen8PrinterID, 
    Kitchen8DesignPath, 
    Kitchen9PrinterName,  
    Kitchen9AltPrinterName, 
    Kitchen9PrinterID, 
    Kitchen9DesignPath, 
    Kitchen10PrinterName, 
    Kitchen10AltPrinterName, 
    Kitchen10PrinterID, 
    Kitchen10DesignPath,  
    Kitchen11PrinterName, 
    Kitchen11AltPrinterName, 
    Kitchen11PrinterID, 
    Kitchen11DesignPath, 
    Kitchen12PrinterName, 
    Kitchen12AltPrinterName, 
    Kitchen12PrinterID,  
    Kitchen12DesignPath, 
    Kitchen13PrinterName, 
    Kitchen13AltPrinterName, 
    Kitchen13PrinterID, 
    Kitchen13DesignPath, 
    Kitchen14PrinterName, 
    Kitchen14AltPrinterName,  
    Kitchen14PrinterID, 
    Kitchen14DesignPath, 
    Kitchen15PrinterName, 
    Kitchen15AltPrinterName, 
    Kitchen15PrinterID, 
    Kitchen15DesignPath, 
    Kitchen16PrinterName,  
    Kitchen16AltPrinterName, 
    Kitchen16PrinterID, 
    Kitchen16DesignPath, 
    Kitchen17PrinterName, 
    Kitchen17AltPrinterName, 
    Kitchen17PrinterID, 
    Kitchen17DesignPath,  
    Kitchen18PrinterName, 
    Kitchen18AltPrinterName, 
    Kitchen18PrinterID, 
    Kitchen18DesignPath, 
    Kitchen19PrinterName, 
    Kitchen19AltPrinterName, 
    Kitchen19PrinterID,  
    Kitchen19DesignPath, 
    Kitchen20PrinterName, 
    Kitchen20AltPrinterName, 
    Kitchen20PrinterID, 
    Kitchen20DesignPath, 
    InvoiceTopFeed, 
    AdditionTopFeed, 
    ISNULL(PrintDineInOrdersKitchen, 1) AS PrintDineInOrdersKitchen,
    ISNULL(PrintBarTableOrdersKitchen, 1) AS PrintBarTableOrdersKitchen,
    ISNULL(PrintTakeOutOrdersKitchen, 1) AS PrintTakeOutOrdersKitchen,
    ISNULL(PrintDriveThruOrdersKitchen, 1) AS PrintDriveThruOrdersKitchen,
    ISNULL(PrintDeliveryOrdersKitchen, 1) AS PrintDeliveryOrdersKitchen,
    [EditKey], 
    [SyncKey], 
    [LabelPrinterID], 
    [LabelPrinterName], 
    [LabelDesignPath], 
    [ReturnPrinterID], 
    [ReturnPrinterName], 
    [ReturnDesignPath] 
FROM StationPrinterSettings  
WHERE StationID = 1;
```[cite: 3]